version: '3.3'
services:
    php-nginx:
            #        ports:
            #            - '80:8080'
        volumes:
            - '~/apps/ahmadz.ai/build:/var/www/html'
        image: trafex/php-nginx
        labels:
          - "traefik.enable=true"
          - "traefik.http.routers.portfolio.rule=Host(`portfolio.ahmadz.ai`, `ahmadz.ai`, `www.ahmadz.ai`)"
          - "traefik.http.routers.portfolio.entrypoints=websecure"
          - "traefik.http.services.portfolio.loadbalancer.server.port=8080"
          - "traefik.http.routers.portfolio.service=portfolio"
          - "traefik.http.routers.portfolio.tls.certresolver=leresolver"
        networks:
          - traefik_net

networks:
    traefik_net:
        external: true
